safe: false
source: .
destination: ./_site
plugins_dir: ./_plugins
highlighter: rouge
markdown: kramdown
exclude: ['CNAME', 'Gemfile', 'Gemfile.lock', 'Rakefile', 'README.md', '.sass-cache', '.asset-cache', '.travis.d']

plugins:
  - jekyll-assets
  - jekyll-last-modified-at
  - jekyll-sitemap

title: "SICE 2020"
description: "The SICE Annual Conference 2020 is an international conference covering a broad range of fields from measurement and control to system analysis and design, from theory to application, and from software to hardware. The conference will be held in Chiang Mai, Thailand in September 22-25 2020."
logo_alt: "SICE 2020 *** September 22-25, 2020 *** Chiang Mai, Thailand"

baseurl: "/sice2020"
url: "https://www.rmutl.ac.th"

google:
  - analytics: UA-83529610-3

## Note. Uncomment and update spreadsheet parameters to enable pulling program
##       data from Google Sheet(s)
program:
  # If the specified file doesn't exist, there will be command-line dialog to create it
  # (Currently hardcoded for a dummy robot.mcrobot.jr@gmail.com account permissions)
  google_client_id: .travis.d/google_client_id.json
  # Google spreadsheet with the conference data
  spreadsheet:
    - "1CpBboHnT_HugUIc1sgOZc-henBHZTD6E0DgbdEq1PsQ" # main

program-at-glance:
  # If the specified file doesn't exist, there will be command-line dialog to create it
  # (Currently hardcoded for a dummy robot.mcrobot.jr@gmail.com account permissions)
  google_client_id: .travis.d/google_client_id.json
  # Google spreadsheet with the conference data
  spreadsheet:
    #- "1Mcgwl3mN0KkAWr9DJOVy9Nx-4iF2kqqEOk5yXK00meo"
    - "1Ds4O1SerZeYmdIaWYn_w4qfmpqXpgPlywUvGo9kxqv8"

assets:
  caching:
    path: .sass-cache/assets
  features:
    automatic_img_size: false
  digest: false

  sources:
    - _assets/css
    - _assets/images
    - _assets/fonts
    - _assets/files
    - _assets/js
    - _assets/bower
    - _assets/calls
    - .sass-cache

  autoprefixer:
    browsers:
      - "last 2 versions"
      - "IE > 9"
